### ISSUE TITLE
undefined method `up_to_date?' for nil:NilClass

### ISSUE THREAD

**Issue by luator** [reednj/git-status-all#1]
When I run `git status-all` in my workspace, for roughly one third of the repositories I get the following error:
> undefined method `up_to_date?' for nil:NilClass

As far as I can tell, there is nothing special with the erroneous repos. When I cd into the directory and run a normal `git st` I get a clean output like the following:

> On branch foo
> Your branch is up-to-date with 'origin/foo'.
> nothing to commit, working directory clean

I am running Ubuntu 16.04 and installed git-status-all with `sudo gem install git-status-all`.

**Comment by reednj** [comment]
ok, interesting, haven't seen that before. Do you not have a local `master` for these repos by any chance? I that could cause this

**Comment by luator** [comment]
You are right, the affected repos follow a non-standard naming scheme and do not a branch called "master".

I was briefly looking at the code, from what I understand the master branch is used to check the remote status(?). Would it not make more sense to check this based on the current branch?
